services:
  - type: web
    name: django-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn taskmanager.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: django-backend.onrender.com
      - key: DB_HOST
        fromDatabase:
          name: taskmanager-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: taskmanager-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: taskmanager-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: taskmanager-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: taskmanager-db
          property: password